### ISSUE TITLE
support other forms of login other than password, depending on config options

### ISSUE THREAD

**Issue by fabius** [matrix-org/dendrite#2026] opened 2021-10-22 07:37 UTC
One should be able to configure which forms of authentication are enabled on a dendrite instance. As stated here https://github.com/matrix-org/dendrite/blob/3b7a4ad640f260b3918a35684b05ced077a09f0c/clientapi/routing/login.go#L62

I'd be happy to work on this unless some work is already in progress. This is somewhat related to the [portable identities proposal](https://github.com/matrix-org/matrix-doc/blob/neilalexander/identities/proposals/2787-portable-identities.md) because it requires a different auth mechanism.

**Comment by kegsay** [comment] 2022-01-21 12:32
Dupe of issues which specify the other forms:
 - JWTS #1626
 - Email #1298 
 - SSO #1297 
 - Tokens #403

**Closed by kegsay** 2022-01-21 12:32 UTC

**Comment by compgeniuses** [comment] 2022-04-04 06:09
> Dupe of issues which specify the other forms:
> 
> * JWTS [JWT login  #1626](https://github.com/matrix-org/dendrite/issues/1626)
> * Email [Implement registering with an email support #1298](https://github.com/matrix-org/dendrite/issues/1298)
> * SSO [Implement SSO for logins #1297](https://github.com/matrix-org/dendrite/issues/1297)
> * Tokens [Login: Implement Token-based authentication #403](https://github.com/matrix-org/dendrite/issues/403)

IF this issue is Closed, shouldnt all other list of issues that specify other form be also closed, for the sake of closure.

Just my thoughts.
