### ISSUE TITLE
Dendrite forgets that I am a member of some rooms

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/dendrite#1128] opened 2020-06-12 21:26 UTC
I have noticed that Dendrite will sometimes forget that I am joined to a room. The room no longer appears in Riot even though I have not left or been kicked from the room.

For example I joined `#dendrite:matrix.org` a while ago and recently noticed that it doesn't appear in my list of rooms anymore.

Happy to provide any logs or database queries that you want. I'm still having the issue I had been having before with joining some rooms so it is possible that my database is screwed up in some way? I haven't done anything to it though so 🤷‍♂️.

Dendrite version:  0dc4cea

The room still exists in `roomserver_rooms`
```
dendrite_roomserver=# SELECT * FROM roomserver_rooms WHERE room_id='!yomrOFwgFXzmeMAbzX:matrix.org';
 room_nid |            room_id             | latest_event_nids | last_event_sent_nid | state_snapshot_nid | room_version
----------+--------------------------------+-------------------+---------------------+--------------------+--------------
        3 | !yomrOFwgFXzmeMAbzX:matrix.org | {}                |               21611 |               5027 | 5
```

```
time="2020-06-12T18:57:33.267822814Z" level=info msg="Incoming request" func=github.com/matrix-org/util.RequestWithLogging file="/usr/home/freebsd/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122" req.id=JudzfRE7ZqHS req.method=GET req.path="/_matrix/client/r0/rooms/!yomrOFwgFXzmeMAbzX:matrix.org/initialSync"
time="2020-06-12T18:57:33.267908364Z" level=info msg="Responding (77 bytes)" func=github.com/matrix-org/util.respond file="/usr/home/freebsd/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170" code=403 req.id=JudzfRE7ZqHS req.method=GET req.path="/_matrix/client/r0/rooms/!yomrOFwgFXzmeMAbzX:matrix.org/initialSync"
```

**Comment by Kegsay** [comment] 2020-06-15 08:48
The only thing we can even remotely delete are room aliases, other than that we don't ever remove things from the roomserver database:
```
$ grep -rin "delete " roomserver
roomserver/storage/postgres/room_aliases_table.go:54:	"DELETE FROM roomserver_room_aliases WHERE alias = $1"
roomserver/storage/sqlite3/room_aliases_table.go:54:	DELETE FROM roomserver_room_aliases WHERE alias = $1
```
It looks like you're using postgres, so perhaps the problem lies there (e.g the database got nuked?)

**Comment by aaronraimist** [comment] 2020-06-16 01:00
I had nuked the database in the past although I thought I had done that before I joined many/any federated rooms. What should I do now? I cannot rejoin the room.

https://gist.github.com/aaronraimist/47030bd8d6d034ca0ba6ab580d2335ae is an example of logs from trying to join it

**Comment by Kegsay** [comment] 2020-06-16 09:58
The `send_join` returns 200 OK so from federation's point of view you will be joined. However, when checking the room's state it needs to verify event signatures which requires public keys. Dendrite attempts to fetch those keys but the servers are dead (the errors you see in the logs) so it cannot verify that the returned state is real.

Currently the only way around this is to fetch keys from a server you trust and is actually alive, which is called a perspective server. I would recommend using matrix.org.

**Comment by Kegsay** [comment] 2020-06-16 09:59
https://github.com/matrix-org/dendrite/blob/master/dendrite-config.yaml#L21

**Comment by Kegsay** [comment] 2020-06-17 10:04
Closing this issue as the cause here is missing keys.

**Closed by Kegsay** 2020-06-17 10:04 UTC
