### ISSUE TITLE
url previews

### ISSUE THREAD

**Issue by TruncatedDinoSour** [matrix-org/dendrite#3321] opened 2024-02-07 17:21 UTC
**Description:**

it explains itself lol, url previews would be nice to have instead of using url preview bots ( such as `@youtube:envs.net` )

**Comment by S7evinK** [comment] 2024-02-28 20:29
Dupe of https://github.com/matrix-org/dendrite/issues/2296

**Closed by S7evinK** 2024-02-28 20:29 UTC
