### ISSUE TITLE
[federation] Querying Keys Through Another Server

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#483] opened 2018-06-06 05:59 UTC
spec: https://matrix.org/docs/spec/server_server/unstable.html#querying-keys-through-another-server

Phase: 3

For this api, federation component needs to send a /_matrix/key/v2/server/ request to another HS, sign the response with it's own key, then return the response.

**Comment by anoadragon453** [comment] 2019-07-17 15:00
Duplicate of https://github.com/matrix-org/dendrite/issues/650

**Closed by anoadragon453** 2019-07-17 15:00 UTC
Labels: component:federation
