### ISSUE TITLE
Can't work very well with sydnent

### ISSUE THREAD

**Issue by mpoes** [matrix-org/dendrite#2538] opened 2022-06-20 11:31 UTC
Can't work very well with sydnent. When binding the email address, click the verification link, sydent shows that the verification is successful, but the client shows that it is unsuccessful. Is there an option for email registration? Like synapse?

**Comment by spaetz** [comment] 2022-06-20 11:39
No, and there is an issue about it: https://github.com/matrix-org/dendrite/issues/1298

**Comment by S7evinK** [comment] 2022-10-20 18:39
Closing this, duplicate of #1298.

**Closed by S7evinK** 2022-10-20 18:39 UTC
