### ISSUE TITLE
Cannot read received messages from different server, others can read mine

### ISSUE THREAD

**Issue by thezeroalpha** [matrix-org/dendrite#1814] opened 2021-03-29 17:00 UTC
### Background information

- **Dendrite version or git SHA**: 0.3.11+af41f6d4
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: go1.15.7 linux/amd64

### Description
I have account "M" (on the matrix.org homeserver via [Element Web](https://app.element.io)) and account "H" (on my own homeserver).
When I send a new message from account M to account H, on account H I see the message "Waiting for this message, this may take a while".
When I send a new message from account H to account M, on account M I see the message without issues.
When I then leave the room on both accounts and create a new room, I can immediately see all new messages sent between the accounts in that room.
I cannot rejoin the previous room, I get the error "No known servers" -- this may be related.

### Steps to reproduce
- Create account "M" on [Element](https://app.element.io) using the matrix.org server
- Send a direct message from M to an account "H" on the personal homeserver
- Send a direct message from account H to account M
- Observe that messages from H to M are visible on M, but messages from M to H are not visible on H
- Leave the room on both accounts
- Create a new direct message room as before, from M to H
- Observe that all messages in that room are now visible to both participants

I would expect that messages in both directions should be visible on both accounts from the start.
I'm not sure what I should look for in the logfiles.

Could someone please help me diagnose this?

PS: the [federation tester](https://federationtester.matrix.org/) checks all succeed.

**Comment by Kegsay** [comment] 2021-04-07 09:56
I assume this room is end-to-end encrypted?

**Comment by thezeroalpha** [comment] 2021-04-08 07:56
Yes, it is.

**Comment by Kegsay** [comment] 2021-04-08 10:34
When you say "not visible" you mean "received but unable to decrypt"?

It seems likely that your server is unable to retrieve device lists correctly, which are required for encryption. Out of interest, do either accounts have non alphanumeric characters in the user ID portion or device ID portion e.g `_-=`? Please list all the special characters if there are some.

I've heard past issues about federated device list queries having incorrect URL escaping, possibly caused by an intermediate reverse proxy, so special characters may indicate this. Further to this, can you please check your logs for any issues around device list queries for the remote server (matrix.org in this case).

**Comment by kegsay** [comment] 2021-07-09 11:20
Possibly related: https://github.com/matrix-org/dendrite/issues/1601

**Comment by S7evinK** [comment] 2022-11-11 13:19
Going to close this, as we're on version 0.10.7 now and E2EE is working much better now.

**Closed by S7evinK** 2022-11-11 13:19 UTC
Labels: bug, component:keyserver

**Comment by thezeroalpha** [comment] 2022-11-12 18:10
Yep thanks, I should've probably closed it myself earlier - the project has developed quite a bit since my issue & I'm not using it at the moment.

**Comment by mispp** [comment] 2023-04-19 20:10
I kinda have an opposite problem: homeserver->matrix.org doesnt work, but matrix.org->homeserver works fine. should i open a new issue regarding this?

if needed:
git -> 72285b2659a31ebd52c91799c17105d81d996f40
monolith
go1.18.10 linux/amd64
postgres
not using docker
