### ISSUE TITLE
Dendrite doesn't urlencode neither : or @ in URL

### ISSUE THREAD

**Issue by maranda** [matrix-org/dendrite#1601] opened 2020-11-30 20:31 UTC
### Background information

- **Dendrite version or git SHA**: 0.3.1+9c52f827
- **Monolith or Polylith?**: Not using it
- **SQLite3 or Postgres?**: Not using it
- **Running in Docker?**: Not using it
- **`go version`**: Not using it

### Steps to reproduce

- Dendrite attempts to fetch device lists from my server instance, running Synapse
- It fails due of Signature Checksum Failure, after the reverse proxy "fixes" the request URL

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

I run a rather exotical setup where IIS with ARR is used as Frontend Proxy and SSL Offloader, which then reverse proxies the requests to NGINX which also mid-frontends and group ups the Synapse workers in the backend patching the URLs as Synapse would expect 'em since ARR canonicalises the URL when proxying requests.

I'm not sure if this is exactly a bug, and once discovered it's rather easy to solve by adjusting the proxy pass ruleset in NGINX. But the fact two implementations behave so far differently on URL encoding when it comes to authenticating and verifying request signatures is bound to cause issues and isn't desiderable.

It's also to note that the same Dendrite instance just seemingly got caught in a loop and continued to try to fetch the device list over and over, very fast, basically flooding the server with requests.

**Comment by Kegsay** [comment] 2020-12-21 10:56
I don't see any evidence of this from our side. Are you sure your setup is re-encoding correctly?

**Comment by maranda** [comment] 2020-12-21 11:00
Yes absolutely, if that wasn't the case the adjustments I did at proxy level wouldn't have fixed the issue.

**Comment by Kegsay** [comment] 2020-12-21 11:24
Can you please supply an affected URL+body and the error synapse produces?

**Comment by maranda** [comment] 2020-12-21 11:55
Unluckily the logs have been long lost in rotations, although I did find a snippet from the Synapse Admins room.

```
Nov 30 14:27:58 akademeia matrix-synapse-worker_federation_reader_2[79118]: 2020-11-30 14:27:58,439 - synapse.federation.transport.server - 312 - WARNING - GET-52638 - authenticate_request failed: 401: Invalid signature for server postal.uber.space with key ed25519:lCLtCF: Unable to verify signature for postal.uber.space: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
Nov 30 14:27:58 akademeia matrix-synapse-worker_federation_reader_2[79118]: 2020-11-30 14:27:58,439 - synapse.http.server - 74 - INFO - GET-52638 - <XForwardedForRequest at 0x7fce7b7c6b50 method='GET' uri='/_matrix/federation/v1/user/devices/%40maranda%3Aaria-net.org' clientproto='HTTP/1.1' site=8085> SynapseError: 401 - Invalid signature for server postal.uber.space with key ed25519:lCLtCF: Unable to verify signature for postal.uber.space: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
Nov 30 14:27:58 akademeia matrix-synapse-worker_federation_reader_2[79118]: 2020-11-30 14:27:58,441 - synapse.access.http.8085 - 310 - INFO - GET-52638 - 185.26.156.217:52938 - 8085 - {None} Processed request: 0.004sec/-0.000sec (0.004sec, 0.000sec) (0.000sec/0.000sec/0) 236B 401 "GET /_matrix/federation/v1/user/devices/%40maranda%3Aaria-net.org HTTP/1.1" "Dendrite/0.3.1+9c52f827" [0 dbevts]
```

So basically Synapse would send "/_matrix/federation/v1/user/devices/%40maranda%3Aaria-net.org" as URI and Dendrite does send "/_matrix/federation/v1/user/devices/@maranda:aria-net.org" instead.

Reference:
https://matrix.to/#/!ehXvUhWNASUkSLvAGP:matrix.org/$4uladbeMUEdpPxD_2AKIWxkNUC4mwM6FaPxzPt1zCCY?via=matrix.org&via=aria-net.org

**Comment by Kegsay** [comment] 2020-12-21 12:20
I don't see any evidence of this happening between dendrite.matrix.org and matrix.org but I'll keep this issue open until I can confirm more broadly.

**Comment by kegsay** [comment] 2021-07-09 10:15
Possibly related: https://github.com/matrix-org/dendrite/issues/1530

**Comment by bones-was-here** [comment] 2022-02-18 08:03
I think this bug is the reason the spaces summary doesn't work even when the experiment is enabled?

**Comment by kegsay** [comment] 2022-12-05 18:01
Closing as I cannot reproduce this.

**Closed by kegsay** 2022-12-05 18:01 UTC
Labels: X-Needs-Info
