### ISSUE TITLE
PFPs Have Difficulty Propogating

### ISSUE THREAD

**Issue by yaliqmadiq** [matrix-org/dendrite#1821] opened 2021-04-08 16:19 UTC
### Background information

- **Dendrite version or git SHA**: b769d5a25ee1dd298899ab9fec0c31e834f9b99e
- **Monolith or Polylith?**: mono
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.16.3

### Description

Changing profile pictures and clicking save in Element either takes minutes or never at all to sync to other users

### Steps to reproduce

- Run dendrite for an hour or so
- Federation is on
- Ask users to update their pfps

This usually resolves by killing and restarting dendrite, then the problem returns.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by Kegsay** [comment] 2021-04-09 15:01
It isn't clear where the problem is here. How many servers are involved? There's too many variables for this to be a meaningful image. I would need logs from servers to see if:
 - The sender server attempted to send the update (or if it was backing off / blacklisted)
 - The receiving server got the update but couldn't process it for some reason
 - The receiving server processed it but clients were not notified for some reason

**Comment by yaliqmadiq** [comment] 2021-04-09 16:51
Only 1 server.

Users on bobrtc.tel changing their pfps can't get them to appear to other users also on bobrtc.tel

**Comment by kegsay** [comment] 2021-07-09 11:21
Seems like a dupe of https://github.com/matrix-org/dendrite/issues/1806 - closing this.

**Closed by kegsay** 2021-07-09 11:21 UTC
Labels: component:federation, needs investigation
