### ISSUE TITLE
How to use email or mobile phone number to register and login?

### ISSUE THREAD

**Issue by zoujiaqing** [matrix-org/dendrite#3318] opened 2024-02-05 18:57 UTC
Email and phone number are the most common registration and login methods.
How to get Dendrite to support them?

**Comment by jjj333-p** [comment] 2024-02-07 04:22
Currently not supported. 

Also reminder that this isnt a support forum, you'll likely get better help in #dendrite:matrix.org

**Comment by TruncatedDinoSour** [comment] 2024-02-07 17:24
> Currently not supported.

but honestly it should be a thing, email is easy, but for phone maybe you could use like twillio api

**Comment by niebloomj** [comment] 2024-02-20 00:54
I think we can close this issue

**Comment by jjj333-p** [comment] 2024-02-20 01:34
or add a [feature request] tag or something

**Comment by S7evinK** [comment] 2024-02-28 20:32
Dupe of https://github.com/matrix-org/dendrite/issues/3260 (probably some others, just doing some cleanup)
And well, currently not implemented.

**Closed by S7evinK** 2024-02-28 20:32 UTC
