### ISSUE TITLE
Dendrite claims namespace is exclusive to a different appservice

### ISSUE THREAD

**Issue by RobinJ1995** [matrix-org/dendrite#1597] opened 2020-11-24 14:32 UTC
### Background information

- **Dendrite version or git SHA**:  `matrixdotorg/dendrite-monolith:v0.3.1` Docker image
- **Monolith or Polylith?**:  Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Docker + Kubernetes
- **`go version`**: Whatever version you guys used to build the binaries included in [the `matrixdotorg/dendrite-monolith:v0.3.1` Docker image](https://hub.docker.com/r/matrixdotorg/dendrite-monolith) :)

### Description

Dendrite seems to be confused about appservice namespace exclusivity.

### Steps to reproduce

1. Setup a clean Dendrite server
1. Setup the [mautrix-telegram](https://github.com/tulir/mautrix-telegram) bridge as an appservice with the following in the registration file;
```
    namespaces:
        users:
        - exclusive: true
          regex: '@telegram_.*:servername'
        - exclusive: true
          regex: '@bridge_telegram:servername'
```
and `bridge_telegram` being the bot username the bridge appservice uses.

3. Start the bridge

The bridge will fail to start with the following error message; `Supplied username bridge_telegram did not match any namespaces for application service ID: matrix_bridge_telegram`.

When setting `exclusive: false` on the `bridge_telegram` rule, the same thing happens when the bot then receives a message and subsequently tries to register a user matching `telegram_*`, which is still marked as exclusive. Setting `exclusive: false` on this rule, too, works around the issue. But it appears to be impossible to have exclusive namespaces, as Dendrite will tell the appservice that it is exclusive to _another_ service (which isn't true, as this is the only appservice on the server).

I have first reported this issue on the mautrix-telegram bridge, and the developer claims that this is an issue with Dendrite. [More info here](https://github.com/tulir/mautrix-telegram/issues/548#issuecomment-733005500).

I have reproduced this issue twice, once on a "production" server, and once on a throwaway install.

**Comment by phol** [comment] 2020-11-24 22:04
I think this is a duplicate of #1518

**Comment by RobinJ1995** [comment] 2020-11-25 23:33
> I think this is a duplicate of #1518

Ah yes, that looks like the same issue.

**Comment by MadLittleMods** [comment] 2020-12-16 06:59
Closing in favor of https://github.com/matrix-org/dendrite/issues/1518

**Closed by MadLittleMods** 2020-12-16 06:59 UTC
Labels: bug, component:appservices
