### ISSUE TITLE
Dendrite tries to pump 26MB messages over Kafka

### ISSUE THREAD

**Issue by RobinJ1995** [matrix-org/dendrite#1620] opened 2020-12-08 15:14 UTC
### Background information

- **Dendrite version or git SHA**: 0.3.2
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: Whatever is in the Docker container
- **Kafka version**: Docker: bitnami/kafka:2.6.0

### Description

Dendrite tries to send pretty huge messages over Kafka when trying to join certain rooms.

### Steps to reproduce

* Set up Dendrite in monolith mode with Postgres and Kafka
* Join a few rooms
* Try to join #fedora:matrix.org
* Watch it try to join for ~10 hours and eventually fail with the following error message hidden in the logs;
```
time="2020-12-08T11:24:12.820136945Z" level=error msg="Write to kafka failed" func="WriteOutputEvents\n\t" file=" [github.com/matrix-org/dendrite/roomserver/internal/input/input.go:113]" error="kafka: Failed to produce message to topic DendriteOutputRoomEvent: kafka server: Message was too large, server rejected it to avoid allocation error." message_bytes=26292271
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment] 2020-12-08 16:01
I think bitnami/kafka should allow 100MB messages (not sure right now if i configured that or if it's the default), so it might be related to the default value of sarama
https://github.com/matrix-org/dendrite/blob/e1d32e2ff1bef346836f6b9d795d33ec49dd3864/dendrite-config.yaml#L83-L87

**Comment by RobinJ1995** [comment] 2020-12-08 16:08
The bug isn't that Kafka doesn't allow huge messages by default, I can fix
(and have) that with configuration. The problem is that message queues
really aren't meant to handle messages of more than 1MB or so, so if
Dendrite is trying to send 26MB messages then something is wrong with its
logic somewhere.

**Comment by S7evinK** [comment] 2020-12-08 17:07
As far as i remember, that just happens once when joining large rooms (i guess the fedora room is also quite large; had the same issue with joining a large room).
Other messages are definitely not that large.

As written in https://github.com/matrix-org/dendrite/pull/1563#issuecomment-716465406:
> Besides changing the `MaxMessageSize`, we could also think about enabling compression in sarama.
> Possible compression codecs: GZIP, Snappy, LZ4, ZSTD
> As with everything related to compression, comes with the trade off of more allocations etc.

But knowing the root cause for the huge amount of events to be added would be good.

**Comment by Kegsay** [comment] 2020-12-21 10:49
The root cause is that joining a room over federation sends a single Kafka message with the join event (forward extremity) along with the *entire room state* which for large rooms is a LOT of events.

**Comment by joh-ku** [comment] 2021-01-31 13:36
I played around with Dendrite configured in `polylith mode` today and ran into the very same issue. I tried to join some rooms at `matrix.org` and Dendrite kept loading without any feedback.

`roomserver.log` finally led me here:
```
time="2021-01-31T10:53:09.634152971Z" level=error msg="Write to kafka failed" func="github.com/matrix-org/dendrite/roomserver/internal/input.(*Inputer).WriteOutputEvents" file="github.com/matrix-org/dendrite/roomserver/internal/input/input.go:111" error="kafka: Failed to produce message to topic DendriteOutputRoomEvent: kafka server: Message was too large, server rejected it to avoid allocation error." message_bytes=1883971
```

When changing `Kafka` and `Dendrite` configuration accordingly, joining rooms is possible, but takes roughly one hour in my case, when joining e.g. `#ubuntu:matrix.org`.

**Comment by kegsay** [comment] 2021-07-09 10:17
We are planning to swap to NATS which has a 1MB size limit.

We will need to resolve this issue and investigate if other messages passed are potentially unbounded.

**Comment by kegsay** [comment] 2021-07-09 10:18
Thoughts @neilalexander ?

**Comment by spaetz** [comment] 2022-01-22 19:39
Just wanted to say that I ran into this issue in the wild with a NATS enabled dendrite, joining a room. The stopgap measure of including @neilalexander patch which bumps the limit to 16mb helped in my case. But that us exactly that, a workaround. It seems trivial to DOS and destroy rooms by adding so many events that the NATS limit is broken.

**Comment by neilalexander** [comment] 2022-01-22 22:07
I have some ideas on what we can do here. I will look into it this week.

**Comment by S7evinK** [comment] 2022-10-20 12:42
Closing this, as with NATS we're now sending single messages in the streams, which shouldn't exceed the mentioned size limit anymore.
If a similar issue appears with a recent version, please create a new issue for this.

**Closed by S7evinK** 2022-10-20 12:42 UTC
Labels: design:scaling, design:components, needs discussion
